apiVersion: v1
kind: Pod
metadata:
        name: mysql-pod
spec:
        containers:
                - name: mysql
                  image: mysql
                  ports:
                     - containerPort: 3306
                  env:
                    - name: MYSQL_ROOT_PASSWORD
                      value: rootpassword
                    - name: MYSQL_USER
                      value: dbuser
                    - name: MYSQL_PASSWORD
                      value: password
                    - name: MYSQL_DATABASE
                      value: simplilearn


