apiVersion: v1
kind: Pod
metadata:
 name: mysql
spec:
 containers:
 - image: mysql
   name: mydatabase
   env:
   - name: MYSQL_ROOT_PASSWORD
     valueFrom:
      secretKeyRef:
       name: dbsecret
       key: MYSQL_ROOT_PASSWORD
   - name: MYSQL_DATABASE
     valueFrom:
      secretKeyRef:
       name: dbsecret
       key: MYSQL_DATABASE
   - name: MYSQL_USER
     valueFrom:
      secretKeyRef:
       name: dbsecret
       key: MYSQL_USER
   - name: MYSQL_PASSWORD
     valueFrom:
      secretKeyRef:
       name: dbsecret
       key: MYSQL_PASSWORD

