apiVersion: v1           #version of api resource
kind: Pod                #api resource
metadata:        #information of the api-resource
   name: taint-pod
spec:                    # configuration/specification of api-resource
   containers:
           - name: demo-pod
             image: nginx
             ports:
                 - containerPort: 80
   tolerations:
      - key: type
        operator: Equal
        value: gpu
        effect: NoSchedule


          

