apiVersion: apps/v1
kind: ReplicaSet
metadata:
        name: replicaset-pod
spec:
    replicas: 10
    selector:
         matchLabels:
               app: my-app
    template:
         metadata:
            labels:     
              app: my-app
         spec:
           containers:      
             - name: replica-pod
               image: nginx

